### PR TITLE
Implement non-amd64 platform pulling

### PR DESCRIPTION
**Pull request by yalh76**

### CODE REVIEW

**Comment by jjlin** [comment]
Thanks for the PR.

As I intended this script to have minimal dependencies though, I don't want to introduce a requirement for `bash` or `jq`.

**Comment by yalh76** [comment]
> Thanks for the PR.
> 
> As I intended this script to have minimal dependencies though, I don't want to introduce a requirement for `bash` or `jq`.

ok, I will try to reduce the requirements but not sure to find a way to not use jq for .json parsing

**Comment by yalh76** [comment]
well... wasn't able to make it with less requirements.

So "implemented/forked" it as an helper for [YunoHost](https://yunohost.org/#/) (Debian based self hosting solution) to lets extract applications from Docker Hub Image instead of building them, to save building time on architectures like RaspberryPi, amd64, etc ...

at https://github.com/YunoHost-Apps/Experimental_helpers/pull/99

**Comment by jjlin** [comment]
I implemented it without `bash` and `jq` in the latest commits. Feel free to give it a try.

**Comment by yalh76** [comment]
So wonderfull, thanks a lots for your work.
It works great even if I haven't tested all :)
I've removed the "fork" of your code in YunoHost helper just to keep YunoHost specific code:

https://github.com/YunoHost-Apps/Experimental_helpers/blob/7772354582ef9b2c2b8ecd828053bd77f2c56bb3/ynh_docker_image_extract/ynh_docker_image_extract#L54

**Pull request closed without merging**
